// generated by compile -asmhdr from package cpu

#define CacheLinePad__size 64
#define option__size 32
#define option_Name 0
#define option_Feature 16
#define option_Specified 24
#define option_Enable 25
#define option_Required 26
#define const_GOARCH &constant.stringVal{mu:sync.Mutex{state:0, sema:0x0}, s:"amd64", l:(*constant.stringVal)(nil), r:(*constant.stringVal)(nil)}
#define const_CacheLinePadSize 64
#define const_cpuid_SSE2 67108864
#define const_cpuid_SSE3 1
#define const_cpuid_PCLMULQDQ 2
#define const_cpuid_SSSE3 512
#define const_cpuid_FMA 4096
#define const_cpuid_SSE41 524288
#define const_cpuid_SSE42 1048576
#define const_cpuid_POPCNT 8388608
#define const_cpuid_AES 33554432
#define const_cpuid_OSXSAVE 134217728
#define const_cpuid_AVX 268435456
#define const_cpuid_BMI1 8
#define const_cpuid_AVX2 32
#define const_cpuid_BMI2 256
#define const_cpuid_ERMS 512
#define const_cpuid_ADX 524288
