// generated by compile -asmhdr from package abi

#define RegArgs__size 272
#define RegArgs_Ints 0
#define RegArgs_Floats 72
#define RegArgs_Ptrs 192
#define RegArgs_ReturnIsPtr 264
#define const_IntArgRegs 9
#define const_FloatArgRegs 15
#define const_EffectiveFloatRegSize 8
